services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebVision\Deepltranslate\Core\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Model}'

  cache.deepltranslateCore:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['deepltranslate_core']
