services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebVision\Deepltranslate\Contribution\:
    resource: '../Classes/*'

  WebVision\Deepltranslate\Contribution\Command\DdevGenerateCommand:
    tags:
      - name: 'console.command'
        command: 'ddev:generate'
        description: 'Generates EXT:styleguide page trees and activates the frontend page.'
        schedulable: false

