name: tests core 10

on:
  push:
  pull_request:
  schedule:
    - cron: '56 4 * * *'

jobs:
  testsuite:
    name: all tests with core v10
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # php-version: [ '7.2', '7.3', '7.4']
        # @todo Limited to 7.4 because of dev dependency not capable with lower php versions
        php-version: [ '7.4']
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2.4

      - name: "Prepare composer dependencies"
        run: ".ddev/scripts/update_version.sh 10"

# @todo Disabled due to much errors - not green currently. Needs to be tackled first.
#      - name: "Verify code against editorconfig"
#        run: "composer ec:check"

# @todo Disabled due fixer errors - needs coordinated cleanup first.
#      - name: "Verify code cgl"
#        run: "composer cs:check"

      - name: "Run TypoScript lint"
        run: "composer lint:typoscript"

      - name: "Run PHP lint"
        run: "composer lint:php"

# @todo Disabled because of PHPStan errors - needs to be made green first
#      - name: "Run PHPStan"
#        run: "composer analyze:php"

      - name: "Unit tests"
        run: "composer test:php:unit"

      - name: "Functional tests"
        run: "composer test:php:unit"
